"""notifications table, richer audit, search indexes

Revision ID: 0974e0679ab0
Revises: b17f0d55b55a
Create Date: 2026-08-25 16:48:06.983471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0974e0679ab0'
down_revision: Union[str, None] = 'b17f0d55b55a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ccc_notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audience_role', sa.String(length=32), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ccc_notification_audience_role'), 'ccc_notification', ['audience_role'], unique=False)
    op.create_index(op.f('ix_ccc_notification_created_at'), 'ccc_notification', ['created_at'], unique=False)
    op.create_index(op.f('ix_ccc_notification_ticket_id'), 'ccc_notification', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_ccc_notification_type'), 'ccc_notification', ['type'], unique=False)
    op.add_column('ccc_event', sa.Column('old_status', sa.String(length=32), nullable=True))
    op.add_column('ccc_event', sa.Column('new_status', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_ccc_ticket_category'), 'ccc_ticket', ['category'], unique=False)
    op.create_index(op.f('ix_ccc_ticket_closed_at'), 'ccc_ticket', ['closed_at'], unique=False)
    op.create_index(op.f('ix_ccc_ticket_created_at'), 'ccc_ticket', ['created_at'], unique=False)
    op.create_index(op.f('ix_ccc_ticket_mmu_vehicle'), 'ccc_ticket', ['mmu_vehicle'], unique=False)
    op.create_index(op.f('ix_ccc_ticket_priority'), 'ccc_ticket', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ccc_ticket_priority'), table_name='ccc_ticket')
    op.drop_index(op.f('ix_ccc_ticket_mmu_vehicle'), table_name='ccc_ticket')
    op.drop_index(op.f('ix_ccc_ticket_created_at'), table_name='ccc_ticket')
    op.drop_index(op.f('ix_ccc_ticket_closed_at'), table_name='ccc_ticket')
    op.drop_index(op.f('ix_ccc_ticket_category'), table_name='ccc_ticket')
    op.drop_column('ccc_event', 'new_status')
    op.drop_column('ccc_event', 'old_status')
    op.drop_index(op.f('ix_ccc_notification_type'), table_name='ccc_notification')
    op.drop_index(op.f('ix_ccc_notification_ticket_id'), table_name='ccc_notification')
    op.drop_index(op.f('ix_ccc_notification_created_at'), table_name='ccc_notification')
    op.drop_index(op.f('ix_ccc_notification_audience_role'), table_name='ccc_notification')
    op.drop_table('ccc_notification')
    # ### end Alembic commands ###
