"""admin portal: teams, categories, admin audit log

Revision ID: 1913fabf3a6b
Revises: 0974e0679ab0
Create Date: 2026-08-26 11:29:38.900350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1913fabf3a6b'
down_revision: Union[str, None] = '0974e0679ab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ccc_admin_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=48), nullable=True),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ccc_admin_event_at'), 'ccc_admin_event', ['at'], unique=False)
    op.create_index(op.f('ix_ccc_admin_event_entity_type'), 'ccc_admin_event', ['entity_type'], unique=False)
    op.create_table('ccc_category',
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('label', sa.String(length=191), nullable=False),
    sa.Column('team_code', sa.String(length=24), nullable=False),
    sa.Column('default_owner', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_ccc_category_team_code'), 'ccc_category', ['team_code'], unique=False)
    op.create_table('ccc_team',
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###

    # Seed data: today's exact hardcoded ROUTING/TEAMS dicts from
    # app/core/config.py at the time of this migration, written as literals
    # (not imported - migrations must stay self-contained snapshots) so
    # routing behaves identically the moment this runs, with zero manual
    # re-entry and zero blast radius on existing tickets (which reference
    # these same string codes and don't need any backfill).
    team_table = sa.table('ccc_team', sa.column('code', sa.String), sa.column('name', sa.String))
    op.bulk_insert(team_table, [
        {"code": "SERVICE", "name": "Service Team"},
        {"code": "QUALITY", "name": "Quality / Application"},
        {"code": "APPLICATION", "name": "Application Team"},
        {"code": "TECHNICAL", "name": "Technical Team"},
        {"code": "NETWORK", "name": "Network Team"},
        {"code": "FIELD_OPS", "name": "Field Operations Team"},
        {"code": "FLEET", "name": "Fleet Team"},
        {"code": "CC_MANAGER", "name": "CC Manager / Technical Team"},
    ])

    category_table = sa.table('ccc_category',
        sa.column('code', sa.String), sa.column('label', sa.String),
        sa.column('team_code', sa.String), sa.column('default_owner', sa.String))
    op.bulk_insert(category_table, [
        {"code": "MACHINE", "label": "Machine / Instrument Breakdown", "team_code": "SERVICE", "default_owner": "Service Engineer"},
        {"code": "QC", "label": "QC Failure / Quality Issue", "team_code": "QUALITY", "default_owner": "Quality Person / Application Person"},
        {"code": "APPLICATION", "label": "Application / Software Issue", "team_code": "APPLICATION", "default_owner": "Application Person"},
        {"code": "TECHNICAL", "label": "General Technical Issue", "team_code": "TECHNICAL", "default_owner": "Technical Team (5 members)"},
        {"code": "LIS", "label": "LIS Connection / Data Transfer", "team_code": "NETWORK", "default_owner": "Network Team (4 members)"},
        {"code": "NETWORK", "label": "Network / Connectivity Issue", "team_code": "NETWORK", "default_owner": "Network Team (4 members)"},
        {"code": "FIELD", "label": "Field Operational Issue", "team_code": "FIELD_OPS", "default_owner": "Field Operations Team"},
        {"code": "FLEET", "label": "Fleet / Vehicle Issue", "team_code": "FLEET", "default_owner": "Fleet Team"},
        {"code": "OTHER", "label": "Other / Unclear Issue", "team_code": "CC_MANAGER", "default_owner": "CC Manager / Technical Team"},
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ccc_team')
    op.drop_index(op.f('ix_ccc_category_team_code'), table_name='ccc_category')
    op.drop_table('ccc_category')
    op.drop_index(op.f('ix_ccc_admin_event_entity_type'), table_name='ccc_admin_event')
    op.drop_index(op.f('ix_ccc_admin_event_at'), table_name='ccc_admin_event')
    op.drop_table('ccc_admin_event')
    # ### end Alembic commands ###
