"""LT self-service: reasons, machines, LT profile fields, visible_to_lt

Revision ID: 21a90c46a15c
Revises: baf0da64af7b
Create Date: 2026-08-28 10:09:35.893852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21a90c46a15c'
down_revision: Union[str, None] = 'baf0da64af7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ccc_machine',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ccc_reason',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('category_code', sa.String(length=24), nullable=False),
    sa.Column('label', sa.String(length=191), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_ccc_reason_category_code'), 'ccc_reason', ['category_code'], unique=False)
    op.add_column('ccc_category', sa.Column('visible_to_lt', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('ccc_ticket', sa.Column('machine_id', sa.Integer(), nullable=True))
    op.add_column('ccc_ticket', sa.Column('reason_codes', sa.JSON(), nullable=True))
    op.add_column('ccc_ticket', sa.Column('photo_path', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_ccc_ticket_machine_id'), 'ccc_ticket', ['machine_id'], unique=False)
    op.add_column('ccc_user', sa.Column('vehicle_id', sa.Integer(), nullable=True))
    op.add_column('ccc_user', sa.Column('district_id', sa.Integer(), nullable=True))
    op.add_column('ccc_user', sa.Column('mandal_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ccc_user_district_id'), 'ccc_user', ['district_id'], unique=False)
    op.create_index(op.f('ix_ccc_user_mandal_id'), 'ccc_user', ['mandal_id'], unique=False)
    op.create_index(op.f('ix_ccc_user_vehicle_id'), 'ccc_user', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ccc_user_vehicle_id'), table_name='ccc_user')
    op.drop_index(op.f('ix_ccc_user_mandal_id'), table_name='ccc_user')
    op.drop_index(op.f('ix_ccc_user_district_id'), table_name='ccc_user')
    op.drop_column('ccc_user', 'mandal_id')
    op.drop_column('ccc_user', 'district_id')
    op.drop_column('ccc_user', 'vehicle_id')
    op.drop_index(op.f('ix_ccc_ticket_machine_id'), table_name='ccc_ticket')
    op.drop_column('ccc_ticket', 'photo_path')
    op.drop_column('ccc_ticket', 'reason_codes')
    op.drop_column('ccc_ticket', 'machine_id')
    op.drop_column('ccc_category', 'visible_to_lt')
    op.drop_index(op.f('ix_ccc_reason_category_code'), table_name='ccc_reason')
    op.drop_table('ccc_reason')
    op.drop_table('ccc_machine')
    # ### end Alembic commands ###
