"""Initial schema

Revision ID: b17f0d55b55a
Revises: 
Create Date: 2026-08-25 15:38:17.784737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b17f0d55b55a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ccc_config',
    sa.Column('k', sa.String(length=64), nullable=False),
    sa.Column('v', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('k')
    )
    op.create_table('ccc_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=48), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ccc_event_ticket_id'), 'ccc_event', ['ticket_id'], unique=False)
    op.create_table('ccc_ticket',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_no', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=24), server_default='CALL', nullable=True),
    sa.Column('mmu_vehicle', sa.String(length=64), nullable=True),
    sa.Column('district', sa.String(length=96), nullable=True),
    sa.Column('location', sa.String(length=191), nullable=True),
    sa.Column('caller_name', sa.String(length=128), nullable=True),
    sa.Column('caller_phone', sa.String(length=20), nullable=True),
    sa.Column('called_at', sa.DateTime(), nullable=True),
    sa.Column('equipment', sa.String(length=128), nullable=True),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=96), nullable=True),
    sa.Column('impact', sa.String(length=191), nullable=True),
    sa.Column('category', sa.String(length=24), nullable=True),
    sa.Column('priority', sa.String(length=4), nullable=True),
    sa.Column('team', sa.String(length=24), nullable=True),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('assignee', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='NEW', nullable=True),
    sa.Column('tat_mins', sa.Integer(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('first_response_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('parts', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('pending_reason', sa.String(length=255), nullable=True),
    sa.Column('confirmed_by', sa.String(length=128), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('escalated', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.Column('escalated_to', sa.String(length=64), nullable=True),
    sa.Column('escalation_note', sa.String(length=255), nullable=True),
    sa.Column('breached', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('reopened', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_no')
    )
    op.create_index(op.f('ix_ccc_ticket_due_at'), 'ccc_ticket', ['due_at'], unique=False)
    op.create_index(op.f('ix_ccc_ticket_status'), 'ccc_ticket', ['status'], unique=False)
    op.create_index(op.f('ix_ccc_ticket_team'), 'ccc_ticket', ['team'], unique=False)
    op.create_table('ccc_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('pw', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ccc_user_username'), 'ccc_user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ccc_user_username'), table_name='ccc_user')
    op.drop_table('ccc_user')
    op.drop_index(op.f('ix_ccc_ticket_team'), table_name='ccc_ticket')
    op.drop_index(op.f('ix_ccc_ticket_status'), table_name='ccc_ticket')
    op.drop_index(op.f('ix_ccc_ticket_due_at'), table_name='ccc_ticket')
    op.drop_table('ccc_ticket')
    op.drop_index(op.f('ix_ccc_event_ticket_id'), table_name='ccc_event')
    op.drop_table('ccc_event')
    op.drop_table('ccc_config')
    # ### end Alembic commands ###
