"""geo hierarchy, vehicle registry, team manager, tiered notification audience

Revision ID: baf0da64af7b
Revises: f429f5f402ce
Create Date: 2026-08-27 12:29:04.624308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baf0da64af7b'
down_revision: Union[str, None] = 'f429f5f402ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ccc_district',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ccc_mandal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district_id', 'name', name='uq_mandal_district_name')
    )
    op.create_index(op.f('ix_ccc_mandal_district_id'), 'ccc_mandal', ['district_id'], unique=False)
    op.create_index(op.f('ix_ccc_mandal_zone_id'), 'ccc_mandal', ['zone_id'], unique=False)
    op.create_table('ccc_vehicle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('registration_no', sa.String(length=32), nullable=False),
    sa.Column('last_mandal_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ccc_vehicle_last_mandal_id'), 'ccc_vehicle', ['last_mandal_id'], unique=False)
    op.create_index(op.f('ix_ccc_vehicle_registration_no'), 'ccc_vehicle', ['registration_no'], unique=True)
    op.create_table('ccc_zone',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('team_code', sa.String(length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_ccc_zone_team_code'), 'ccc_zone', ['team_code'], unique=False)
    op.add_column('ccc_category', sa.Column('route_by_zone', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('ccc_notification', sa.Column('audience_username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_ccc_notification_audience_username'), 'ccc_notification', ['audience_username'], unique=False)
    op.add_column('ccc_ticket', sa.Column('vehicle_id', sa.Integer(), nullable=True))
    op.add_column('ccc_ticket', sa.Column('district_id', sa.Integer(), nullable=True))
    op.add_column('ccc_ticket', sa.Column('mandal_id', sa.Integer(), nullable=True))
    op.add_column('ccc_ticket', sa.Column('zone_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ccc_ticket_district_id'), 'ccc_ticket', ['district_id'], unique=False)
    op.create_index(op.f('ix_ccc_ticket_mandal_id'), 'ccc_ticket', ['mandal_id'], unique=False)
    op.create_index(op.f('ix_ccc_ticket_vehicle_id'), 'ccc_ticket', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_ccc_ticket_zone_id'), 'ccc_ticket', ['zone_id'], unique=False)
    op.add_column('ccc_user', sa.Column('hr_emp_code', sa.String(length=32), nullable=True))
    op.add_column('ccc_user', sa.Column('reporting_manager_id', sa.Integer(), nullable=True))
    op.add_column('ccc_user', sa.Column('is_team_manager', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.create_index(op.f('ix_ccc_user_reporting_manager_id'), 'ccc_user', ['reporting_manager_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ccc_user_reporting_manager_id'), table_name='ccc_user')
    op.drop_column('ccc_user', 'is_team_manager')
    op.drop_column('ccc_user', 'reporting_manager_id')
    op.drop_column('ccc_user', 'hr_emp_code')
    op.drop_index(op.f('ix_ccc_ticket_zone_id'), table_name='ccc_ticket')
    op.drop_index(op.f('ix_ccc_ticket_vehicle_id'), table_name='ccc_ticket')
    op.drop_index(op.f('ix_ccc_ticket_mandal_id'), table_name='ccc_ticket')
    op.drop_index(op.f('ix_ccc_ticket_district_id'), table_name='ccc_ticket')
    op.drop_column('ccc_ticket', 'zone_id')
    op.drop_column('ccc_ticket', 'mandal_id')
    op.drop_column('ccc_ticket', 'district_id')
    op.drop_column('ccc_ticket', 'vehicle_id')
    op.drop_index(op.f('ix_ccc_notification_audience_username'), table_name='ccc_notification')
    op.drop_column('ccc_notification', 'audience_username')
    op.drop_column('ccc_category', 'route_by_zone')
    op.drop_index(op.f('ix_ccc_zone_team_code'), table_name='ccc_zone')
    op.drop_table('ccc_zone')
    op.drop_index(op.f('ix_ccc_vehicle_registration_no'), table_name='ccc_vehicle')
    op.drop_index(op.f('ix_ccc_vehicle_last_mandal_id'), table_name='ccc_vehicle')
    op.drop_table('ccc_vehicle')
    op.drop_index(op.f('ix_ccc_mandal_zone_id'), table_name='ccc_mandal')
    op.drop_index(op.f('ix_ccc_mandal_district_id'), table_name='ccc_mandal')
    op.drop_table('ccc_mandal')
    op.drop_table('ccc_district')
    # ### end Alembic commands ###
