"""sla-pausing pending, time-limited reopen, vip escalation

Revision ID: f429f5f402ce
Revises: 1913fabf3a6b
Create Date: 2026-08-27 10:34:37.374547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f429f5f402ce'
down_revision: Union[str, None] = '1913fabf3a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ccc_ticket', sa.Column('pending_since', sa.DateTime(), nullable=True))
    op.add_column('ccc_ticket', sa.Column('paused_minutes', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('ccc_ticket', sa.Column('vip', sa.Boolean(), server_default=sa.text('0'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ccc_ticket', 'vip')
    op.drop_column('ccc_ticket', 'paused_minutes')
    op.drop_column('ccc_ticket', 'pending_since')
    # ### end Alembic commands ###
