from sqlalchemy import Column, Integer, String, Boolean, DateTime, Text, text
from sqlalchemy.sql import func
from app.db.database import Base

class Ticket(Base):
    __tablename__ = "ccc_ticket"

    id = Column(Integer, primary_key=True, autoincrement=True)
    ticket_no = Column(String(32), unique=True)
    source = Column(String(24), server_default='CALL')
    mmu_vehicle = Column(String(64), index=True)
    district = Column(String(96))
    location = Column(String(191))
    caller_name = Column(String(128))
    caller_phone = Column(String(20))
    called_at = Column(DateTime)
    equipment = Column(String(128))
    problem = Column(Text)
    error_code = Column(String(96))
    impact = Column(String(191))
    category = Column(String(24), index=True)
    priority = Column(String(4), index=True)
    team = Column(String(24), index=True)
    owner = Column(String(128))
    assignee = Column(String(64))
    status = Column(String(32), server_default='NEW', index=True)
    tat_mins = Column(Integer)
    due_at = Column(DateTime, index=True)
    created_at = Column(DateTime, default=func.now(), index=True)
    created_by = Column(String(64))
    assigned_at = Column(DateTime)
    acknowledged_at = Column(DateTime)
    first_response_at = Column(DateTime)
    resolved_at = Column(DateTime)
    closed_at = Column(DateTime, index=True)
    diagnosis = Column(Text)
    action_taken = Column(Text)
    root_cause = Column(Text)
    parts = Column(Text)
    resolution = Column(Text)
    pending_reason = Column(String(255))
    confirmed_by = Column(String(128))
    confirmed_at = Column(DateTime)
    escalated = Column(Boolean, server_default=text("0"))
    escalated_at = Column(DateTime)
    escalated_to = Column(String(64))
    escalation_note = Column(String(255))
    breached = Column(Boolean, server_default=text("0"))
    reopened = Column(Integer, server_default=text("0"))
